<?php 

   return [
      ''            => array('name' => ''),
    	'ace'         => array('name' => 'Achinese',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Aceh'),
		'af'          => array('name' => 'Afrikaans',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Afrikaans'),
		'agq'         => array('name' => 'Aghem',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Aghem'),
		'ak'          => array('name' => 'Akan',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Akan'),
		'an'          => array('name' => 'Aragonese',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'aragonÃ©s'),
		'cch'         => array('name' => 'Atsam',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Atsam'),
		'gn'          => array('name' => 'GuaranÃ­',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'AvaÃ±eâ€™áº½'),
		'ae'          => array('name' => 'Avestan',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'avesta'),
		'ay'          => array('name' => 'Aymara',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'aymar aru'),
		'az'          => array('name' => 'Azerbaijani (Latin)',    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'azÉ™rbaycanca'),
		'id'          => array('name' => 'Indonesian',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Bahasa Indonesia'),
		'ms'          => array('name' => 'Malay',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Bahasa Melayu'),
		'bm'          => array('name' => 'Bambara',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'bamanakan'),
		'jv'          => array('name' => 'Javanese (Latin)',       'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Basa Jawa'),
		'su'          => array('name' => 'Sundanese',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Basa Sunda'),
		'bh'          => array('name' => 'Bihari',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Bihari'),
		'bi'          => array('name' => 'Bislama',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Bislama'),
		'nb'          => array('name' => 'Norwegian BokmÃ¥l',      'script' => 'Latn', 'dir' => 'ltr', 'native' => 'BokmÃ¥l'),
		'bs'          => array('name' => 'Bosnian',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'bosanski'),
		'br'          => array('name' => 'Breton',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'brezhoneg'),
		'ca'          => array('name' => 'Catalan',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'catalÃ '),
		'ch'          => array('name' => 'Chamorro',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Chamoru'),
		'ny'          => array('name' => 'Chewa',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'chiCheÅµa'),
		'kde'         => array('name' => 'Makonde',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Chimakonde'),
		'sn'          => array('name' => 'Shona',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'chiShona'),
		'co'          => array('name' => 'Corsican',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'corsu'),
		'cy'          => array('name' => 'Welsh',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Cymraeg'),
		'da'          => array('name' => 'Danish',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'dansk'),
		'se'          => array('name' => 'Northern Sami',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'davvisÃ¡megiella'),
		'de'          => array('name' => 'German',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Deutsch'),
		'luo'         => array('name' => 'Luo',                    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Dholuo'),
		'nv'          => array('name' => 'Navajo',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'DinÃ© bizaad'),
		'dua'         => array('name' => 'Duala',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'duÃ¡lÃ¡'),
		'et'          => array('name' => 'Estonian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'eesti'),
		'na'          => array('name' => 'Nauru',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'EkakairÅ© Naoero'),
		'guz'         => array('name' => 'Ekegusii',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ekegusii'),
		'en'          => array('name' => 'English',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'English'),
		'en-AU'       => array('name' => 'Australian English',     'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Australian English'),
		'en-GB'       => array('name' => 'British English',        'script' => 'Latn', 'dir' => 'ltr', 'native' => 'British English'),
		'en-US'       => array('name' => 'U.S. English',           'script' => 'Latn', 'dir' => 'ltr', 'native' => 'U.S. English'),
		'es'          => array('name' => 'Spanish',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'espaÃ±ol'),
		'eo'          => array('name' => 'Esperanto',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'esperanto'),
		'eu'          => array('name' => 'Basque',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'euskara'),
		'ewo'         => array('name' => 'Ewondo',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'ewondo'),
		'ee'          => array('name' => 'Ewe',                    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'eÊ‹egbe'),
		'fil'         => array('name' => 'Filipino',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Filipino'),
		'fr'          => array('name' => 'French',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'franÃ§ais'),
		'fr-CA'       => array('name' => 'Canadian French',        'script' => 'Latn', 'dir' => 'ltr', 'native' => 'franÃ§ais canadien'),
		'fy'          => array('name' => 'Western Frisian',        'script' => 'Latn', 'dir' => 'ltr', 'native' => 'frysk'),
		'fur'         => array('name' => 'Friulian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'furlan'),
		'fo'          => array('name' => 'Faroese',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'fÃ¸royskt'),
		'gaa'         => array('name' => 'Ga',                     'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ga'),
		'ga'          => array('name' => 'Irish',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Gaeilge'),
		'gv'          => array('name' => 'Manx',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Gaelg'),
		'sm'          => array('name' => 'Samoan',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Gagana faâ€™a SÄ�moa'),
		'gl'          => array('name' => 'Galician',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'galego'),
		'ki'          => array('name' => 'Kikuyu',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Gikuyu'),
		'gd'          => array('name' => 'Scottish Gaelic',        'script' => 'Latn', 'dir' => 'ltr', 'native' => 'GÃ idhlig'),
		'ha'          => array('name' => 'Hausa',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Hausa'),
		'bez'         => array('name' => 'Bena',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Hibena'),
		'ho'          => array('name' => 'Hiri Motu',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Hiri Motu'),
		'hr'          => array('name' => 'Croatian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'hrvatski'),
		'bem'         => array('name' => 'Bemba',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ichibemba'),
		'io'          => array('name' => 'Ido',                    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ido'),
		'ig'          => array('name' => 'Igbo',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Igbo'),
		'rn'          => array('name' => 'Rundi',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ikirundi'),
		'ia'          => array('name' => 'Interlingua',            'script' => 'Latn', 'dir' => 'ltr', 'native' => 'interlingua'),
		'iu-Latn'     => array('name' => 'Inuktitut (Latin)',      'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Inuktitut'),
		'sbp'         => array('name' => 'Sileibi',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ishisangu'),
		'nd'          => array('name' => 'North Ndebele',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'isiNdebele'),
		'nr'          => array('name' => 'South Ndebele',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'isiNdebele'),
		'xh'          => array('name' => 'Xhosa',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'isiXhosa'),
		'zu'          => array('name' => 'Zulu',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'isiZulu'),
		'it'          => array('name' => 'Italian',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'italiano'),
		'ik'          => array('name' => 'Inupiaq',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'IÃ±upiaq'),
		'dyo'         => array('name' => 'Jola-Fonyi',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'joola'),
		'kea'         => array('name' => 'Kabuverdianu',           'script' => 'Latn', 'dir' => 'ltr', 'native' => 'kabuverdianu'),
		'kaj'         => array('name' => 'Jju',                    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kaje'),
		'mh'          => array('name' => 'Marshallese',            'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kajin MÌ§ajeÄ¼'),
		'kl'          => array('name' => 'Kalaallisut',            'script' => 'Latn', 'dir' => 'ltr', 'native' => 'kalaallisut'),
		'kln'         => array('name' => 'Kalenjin',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kalenjin'),
		'kr'          => array('name' => 'Kanuri',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kanuri'),
		'kcg'         => array('name' => 'Tyap',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Katab'),
		'kw'          => array('name' => 'Cornish',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'kernewek'),
		'naq'         => array('name' => 'Nama',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Khoekhoegowab'),
		'rof'         => array('name' => 'Rombo',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kihorombo'),
		'kam'         => array('name' => 'Kamba',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kikamba'),
		'kg'          => array('name' => 'Kongo',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kikongo'),
		'jmc'         => array('name' => 'Machame',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kimachame'),
		'rw'          => array('name' => 'Kinyarwanda',            'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kinyarwanda'),
		'asa'         => array('name' => 'Kipare',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kipare'),
		'rwk'         => array('name' => 'Rwa',                    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kiruwa'),
		'saq'         => array('name' => 'Samburu',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kisampur'),
		'ksb'         => array('name' => 'Shambala',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kishambaa'),
		'swc'         => array('name' => 'Congo Swahili',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kiswahili ya Kongo'),
		'sw'          => array('name' => 'Swahili',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kiswahili'),
		'dav'         => array('name' => 'Dawida',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kitaita'),
		'teo'         => array('name' => 'Teso',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kiteso'),
		'khq'         => array('name' => 'Koyra Chiini',           'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Koyra ciini'),
		'ses'         => array('name' => 'Songhay',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Koyraboro senni'),
		'mfe'         => array('name' => 'Morisyen',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'kreol morisien'),
		'ht'          => array('name' => 'Haitian',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'KreyÃ²l ayisyen'),
		'kj'          => array('name' => 'Kuanyama',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Kwanyama'),
		'ksh'         => array('name' => 'KÃ¶lsch',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'KÃ¶lsch'),
		'ebu'         => array('name' => 'Kiembu',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'KÄ©embu'),
		'mer'         => array('name' => 'KimÃ®Ã®ru',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'KÄ©mÄ©rÅ©'),
		'lag'         => array('name' => 'Langi',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'KÉ¨laangi'),
		'lah'         => array('name' => 'Lahnda',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Lahnda'),
		'la'          => array('name' => 'Latin',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'latine'),
		'lv'          => array('name' => 'Latvian',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'latvieÅ¡u'),
		'to'          => array('name' => 'Tongan',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'lea fakatonga'),
		'lt'          => array('name' => 'Lithuanian',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'lietuviÅ³'),
		'li'          => array('name' => 'Limburgish',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Limburgs'),
		'ln'          => array('name' => 'Lingala',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'lingÃ¡la'),
		'lg'          => array('name' => 'Ganda',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Luganda'),
		'luy'         => array('name' => 'Oluluyia',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Luluhia'),
		'lb'          => array('name' => 'Luxembourgish',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'LÃ«tzebuergesch'),
		'hu'          => array('name' => 'Hungarian',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'magyar'),
		'mgh'         => array('name' => 'Makhuwa-Meetto',         'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Makua'),
		'mg'          => array('name' => 'Malagasy',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Malagasy'),
		'mt'          => array('name' => 'Maltese',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Malti'),
		'mtr'         => array('name' => 'Mewari',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Mewari'),
		'mua'         => array('name' => 'Mundang',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Mundang'),
		'mi'          => array('name' => 'MÄ�ori',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'MÄ�ori'),
		'nl'          => array('name' => 'Dutch',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Nederlands'),
		'nmg'         => array('name' => 'Kwasio',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'ngumba'),
		'yav'         => array('name' => 'Yangben',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'nuasue'),
		'nn'          => array('name' => 'Norwegian Nynorsk',      'script' => 'Latn', 'dir' => 'ltr', 'native' => 'nynorsk'),
		'oc'          => array('name' => 'Occitan',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'occitan'),
		'ang'         => array('name' => 'Old English',            'script' => 'Runr', 'dir' => 'ltr', 'native' => 'Old English'),
		'xog'         => array('name' => 'Soga',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Olusoga'),
		'om'          => array('name' => 'Oromo',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Oromoo'),
		'ng'          => array('name' => 'Ndonga',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'OshiNdonga'),
		'hz'          => array('name' => 'Herero',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Otjiherero'),
		'uz-Latn'     => array('name' => 'Uzbek (Latin)',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'oÊ¼zbekcha'),
		'nds'         => array('name' => 'Low German',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'PlattdÃ¼Ã¼tsch'),
		'pl'          => array('name' => 'Polish',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'polski'),
		'pt'          => array('name' => 'Portuguese',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'portuguÃªs'),
		'pt-BR'       => array('name' => 'Brazilian Portuguese',   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'portuguÃªs do Brasil'),
		'ff'          => array('name' => 'Fulah',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Pulaar'),
		'pi'          => array('name' => 'Pahari-Potwari',         'script' => 'Latn', 'dir' => 'ltr', 'native' => 'PÄ�li'),
		'aa'          => array('name' => 'Afar',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Qafar'),
		'ty'          => array('name' => 'Tahitian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Reo MÄ�ohi'),
		'ksf'         => array('name' => 'Bafia',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'rikpa'),
		'ro'          => array('name' => 'Romanian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'romÃ¢nÄƒ'),
		'cgg'         => array('name' => 'Chiga',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Rukiga'),
		'rm'          => array('name' => 'Romansh',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'rumantsch'),
		'qu'          => array('name' => 'Quechua',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Runa Simi'),
		'nyn'         => array('name' => 'Nyankole',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Runyankore'),
		'ssy'         => array('name' => 'Saho',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Saho'),
		'sc'          => array('name' => 'Sardinian',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'sardu'),
		'de-CH'       => array('name' => 'Swiss High German',      'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Schweizer Hochdeutsch'),
		'gsw'         => array('name' => 'Swiss German',           'script' => 'Latn', 'dir' => 'ltr', 'native' => 'SchwiizertÃ¼Ã¼tsch'),
		'trv'         => array('name' => 'Taroko',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Seediq'),
		'seh'         => array('name' => 'Sena',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'sena'),
		'nso'         => array('name' => 'Northern Sotho',         'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Sesotho sa Leboa'),
		'st'          => array('name' => 'Southern Sotho',         'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Sesotho'),
		'tn'          => array('name' => 'Tswana',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Setswana'),
		'sq'          => array('name' => 'Albanian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'shqip'),
		'sid'         => array('name' => 'Sidamo',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Sidaamu Afo'),
		'ss'          => array('name' => 'Swati',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Siswati'),
		'sk'          => array('name' => 'Slovak',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'slovenÄ�ina'),
		'sl'          => array('name' => 'Slovene',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'slovenÅ¡Ä�ina'),
		'so'          => array('name' => 'Somali',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Soomaali'),
		'sr-Latn'     => array('name' => 'Serbian (Latin)',        'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Srpski'),
		'sh'          => array('name' => 'Serbo-Croatian',         'script' => 'Latn', 'dir' => 'ltr', 'native' => 'srpskohrvatski'),
		'fi'          => array('name' => 'Finnish',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'suomi'),
		'sv'          => array('name' => 'Swedish',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'svenska'),
		'sg'          => array('name' => 'Sango',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'SÃ¤ngÃ¶'),
		'tl'          => array('name' => 'Tagalog',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tagalog'),
		'tzm-Latn'    => array('name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tamazight'),
		'kab'         => array('name' => 'Kabyle',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Taqbaylit'),
		'twq'         => array('name' => 'Tasawaq',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tasawaq senni'),
		'shi'         => array('name' => 'Tachelhit (Latin)',      'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tashelhit'),
		'nus'         => array('name' => 'Nuer',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Thok Nath'),
		'vi'          => array('name' => 'Vietnamese',             'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tiáº¿ng Viá»‡t'),
		'tg-Latn'     => array('name' => 'Tajik (Latin)',          'script' => 'Latn', 'dir' => 'ltr', 'native' => 'tojikÄ«'),
		'lu'          => array('name' => 'Luba-Katanga',           'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tshiluba'),
		've'          => array('name' => 'Venda',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Tshivená¸“a'),
		'tw'          => array('name' => 'Twi',                    'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Twi'),
		'tr'          => array('name' => 'Turkish',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'TÃ¼rkÃ§e'),
		'ale'         => array('name' => 'Aleut',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Unangax tunuu'),
		'ca-valencia' => array('name' => 'Valencian',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'valenciÃ '),
		'vai-Latn'    => array('name' => 'Vai (Latin)',            'script' => 'Latn', 'dir' => 'ltr', 'native' => 'ViyamÃ­Ä©'),
		'vo'          => array('name' => 'VolapÃ¼k',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'VolapÃ¼k'),
		'fj'          => array('name' => 'Fijian',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'vosa Vakaviti'),
		'wa'          => array('name' => 'Walloon',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Walon'),
		'wae'         => array('name' => 'Walser',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Walser'),
		'wen'         => array('name' => 'Sorbian',                'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Wendic'),
		'wo'          => array('name' => 'Wolof',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Wolof'),
		'ts'          => array('name' => 'Tsonga',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Xitsonga'),
		'dje'         => array('name' => 'Zarma',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Zarmaciine'),
		'yo'          => array('name' => 'Yoruba',                 'script' => 'Latn', 'dir' => 'ltr', 'native' => 'ÃˆdÃ¨ YorÃ¹bÃ¡'),
		'de-AT'       => array('name' => 'Austrian German',        'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ã–sterreichisches Deutsch'),
		'is'          => array('name' => 'Icelandic',              'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ã­slenska'),
		'cs'          => array('name' => 'Czech',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ä�eÅ¡tina'),
		'bas'         => array('name' => 'Basa',                   'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Æ�Ã sÃ a'),
		'mas'         => array('name' => 'Masai',                  'script' => 'Latn', 'dir' => 'ltr', 'native' => 'É”l-Maa'),
		'haw'         => array('name' => 'Hawaiian',               'script' => 'Latn', 'dir' => 'ltr', 'native' => 'Ê»ÅŒlelo HawaiÊ»i'),
		'el'          => array('name' => 'Greek',                  'script' => 'Grek', 'dir' => 'ltr', 'native' => 'Î•Î»Î»Î·Î½Î¹ÎºÎ¬'),
		'uz'          => array('name' => 'Uzbek (Cyrillic)',       'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'ÐŽÐ·Ð±ÐµÐº'),
		'az-Cyrl'     => array('name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð�Ð·Ó™Ñ€Ð±Ð°Ñ˜Ò¹Ð°Ð½'),
		'ab'          => array('name' => 'Abkhazian',              'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð�Ò§Ñ�ÑƒÐ°'),
		'os'          => array('name' => 'Ossetic',                'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð˜Ñ€Ð¾Ð½'),
		'ky'          => array('name' => 'Kyrgyz',                 'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'ÐšÑ‹Ñ€Ð³Ñ‹Ð·'),
		'sr'          => array('name' => 'Serbian (Cyrillic)',     'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð¡Ñ€Ð¿Ñ�ÐºÐ¸'),
		'av'          => array('name' => 'Avaric',                 'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð°Ð²Ð°Ñ€ Ð¼Ð°Ñ†Ó€'),
		'ady'         => array('name' => 'Adyghe',                 'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð°Ð´Ñ‹Ð³Ñ�Ð±Ð·Ñ�'),
		'ba'          => array('name' => 'Bashkir',                'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð±Ð°ÑˆÒ¡Ð¾Ñ€Ñ‚ Ñ‚ÐµÐ»Ðµ'),
		'be'          => array('name' => 'Belarusian',             'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð±ÐµÐ»Ð°Ñ€ÑƒÑ�ÐºÐ°Ñ�'),
		'bg'          => array('name' => 'Bulgarian',              'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð±ÑŠÐ»Ð³Ð°Ñ€Ñ�ÐºÐ¸'),
		'kv'          => array('name' => 'Komi',                   'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'ÐºÐ¾Ð¼Ð¸ ÐºÑ‹Ð²'),
		'mk'          => array('name' => 'Macedonian',             'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð¼Ð°ÐºÐµÐ´Ð¾Ð½Ñ�ÐºÐ¸'),
		'mn'          => array('name' => 'Mongolian (Cyrillic)',   'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð¼Ð¾Ð½Ð³Ð¾Ð»'),
		'ce'          => array('name' => 'Chechen',                'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ð½Ð¾Ñ…Ñ‡Ð¸Ð¹Ð½ Ð¼Ð¾Ñ‚Ñ‚'),
		'ru'          => array('name' => 'Russian',                'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ€ÑƒÑ�Ñ�ÐºÐ¸Ð¹'),
		'sah'         => array('name' => 'Yakut',                  'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ�Ð°Ñ…Ð° Ñ‚Ñ‹Ð»Ð°'),
		'tt'          => array('name' => 'Tatar',                  'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ‚Ð°Ñ‚Ð°Ñ€ Ñ‚ÐµÐ»Ðµ'),
		'tg'          => array('name' => 'Tajik (Cyrillic)',       'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ‚Ð¾Ò·Ð¸ÐºÓ£'),
		'tk'          => array('name' => 'Turkmen',                'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ‚Ò¯Ñ€ÐºÐ¼ÐµÐ½Ñ‡Ðµ'),
		'uk'          => array('name' => 'Ukrainian',              'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'ÑƒÐºÑ€Ð°Ñ—Ð½Ñ�ÑŒÐºÐ°'),
		'cv'          => array('name' => 'Chuvash',                'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ‡Ó‘Ð²Ð°Ñˆ Ñ‡Ó—Ð»Ñ…Ð¸'),
		'cu'          => array('name' => 'Church Slavic',          'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ñ©Ð·Ñ‹ÐºÑŠ Ñ�Ð»Ð¾Ð²Ñ£Ð½ÑŒÑ�ÐºÑŠ'),
		'kk'          => array('name' => 'Kazakh',                 'script' => 'Cyrl', 'dir' => 'ltr', 'native' => 'Ò›Ð°Ð·Ð°Ò› Ñ‚Ñ–Ð»Ñ–'),
		'hy'          => array('name' => 'Armenian',               'script' => 'Armn', 'dir' => 'ltr', 'native' => 'Õ€Õ¡ÕµÕ¥Ö€Õ§Õ¶'),
		'yi'          => array('name' => 'Yiddish',                'script' => 'Hebr', 'dir' => 'rtl', 'native' => '×™×™Ö´×“×™×©'),
		'he'          => array('name' => 'Hebrew',                 'script' => 'Hebr', 'dir' => 'rtl', 'native' => '×¢×‘×¨×™×ª'),
		'ug'          => array('name' => 'Uyghur',                 'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ø¦Û‡ÙŠØºÛ‡Ø±Ú†Û•'),
		'ur'          => array('name' => 'Urdu',                   'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ø§Ø±Ø¯Ùˆ'),
		'ar'          => array('name' => 'Arabic',                 'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©'),
		'uz-Arab'     => array('name' => 'Uzbek (Arabic)',         'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ø§Û‰Ø²Ø¨Û�Ú©'),
		'tg-Arab'     => array('name' => 'Tajik (Arabic)',         'script' => 'Arab', 'dir' => 'rtl', 'native' => 'ØªØ§Ø¬ÛŒÚ©ÛŒ'),
		'sd'          => array('name' => 'Sindhi',                 'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ø³Ù†ÚŒÙŠ'),
		'fa'          => array('name' => 'Persian',                'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ù�Ø§Ø±Ø³ÛŒ'),
		'pa-Arab'     => array('name' => 'Punjabi (Arabic)',       'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ù¾Ù†Ø¬Ø§Ø¨'),
		'ps'          => array('name' => 'Pashto',                 'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ù¾ÚšØªÙˆ'),
		'ks'          => array('name' => 'Kashmiri (Arabic)',      'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ú©Ø£Ø´Ù�Ø±'),
		'ku'          => array('name' => 'Kurdish',                'script' => 'Arab', 'dir' => 'rtl', 'native' => 'Ú©ÙˆØ±Ø¯ÛŒ'),
		'dv'          => array('name' => 'Divehi',                 'script' => 'Thaa', 'dir' => 'rtl', 'native' => 'Þ‹Þ¨ÞˆÞ¬Þ€Þ¨Þ„Þ¦Þ�Þ°'),
		'ks-Deva'     => array('name' => 'Kashmiri (Devaganari)',  'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤•à¥‰à¤¶à¥�à¤°'),
		'kok'         => array('name' => 'Konkani',                'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤•à¥‹à¤‚à¤•à¤£à¥€'),
		'doi'         => array('name' => 'Dogri',                  'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤¡à¥‹à¤—à¤°à¥€'),
		'ne'          => array('name' => 'Nepali',                 'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤¨à¥‡à¤ªà¤¾à¤²à¥€'),
		'pra'         => array('name' => 'Prakrit',                'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤ªà¥�à¤°à¤¾à¤•à¥ƒà¤¤'),
		'brx'         => array('name' => 'Bodo',                   'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤¬à¤¡à¤¼à¥‹'),
		'bra'         => array('name' => 'Braj',                   'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤¬à¥�à¤°à¤œ à¤­à¤¾à¤·à¤¾'),
		'mr'          => array('name' => 'Marathi',                'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤®à¤°à¤¾à¤ à¥€'),
		'mai'         => array('name' => 'Maithili',               'script' => 'Tirh', 'dir' => 'ltr', 'native' => 'à¤®à¥ˆà¤¥à¤¿à¤²à¥€'),
		'raj'         => array('name' => 'Rajasthani',             'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤°à¤¾à¤œà¤¸à¥�à¤¥à¤¾à¤¨à¥€'),
		'sa'          => array('name' => 'Sanskrit',               'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤¸à¤‚à¤¸à¥�à¤•à¥ƒà¤¤à¤®à¥�'),
		'hi'          => array('name' => 'Hindi',                  'script' => 'Deva', 'dir' => 'ltr', 'native' => 'à¤¹à¤¿à¤¨à¥�à¤¦à¥€'),
		'as'          => array('name' => 'Assamese',               'script' => 'Beng', 'dir' => 'ltr', 'native' => 'à¦…à¦¸à¦®à§€à¦¯à¦¼à¦¾'),
		'bn'          => array('name' => 'Bengali',                'script' => 'Beng', 'dir' => 'ltr', 'native' => 'à¦¬à¦¾à¦‚à¦²à¦¾'),
		'mni'         => array('name' => 'Manipuri',               'script' => 'Beng', 'dir' => 'ltr', 'native' => 'à¦®à§ˆà¦¤à§ˆ'),
		'pa'          => array('name' => 'Punjabi (Gurmukhi)',     'script' => 'Guru', 'dir' => 'ltr', 'native' => 'à¨ªà©°à¨œà¨¾à¨¬à©€'),
		'gu'          => array('name' => 'Gujarati',               'script' => 'Gujr', 'dir' => 'ltr', 'native' => 'àª—à«�àªœàª°àª¾àª¤à«€'),
		'or'          => array('name' => 'Oriya',                  'script' => 'Orya', 'dir' => 'ltr', 'native' => 'à¬“à¬¡à¬¼à¬¿à¬†'),
		'ta'          => array('name' => 'Tamil',                  'script' => 'Taml', 'dir' => 'ltr', 'native' => 'à®¤à®®à®¿à®´à¯�'),
		'te'          => array('name' => 'Telugu',                 'script' => 'Telu', 'dir' => 'ltr', 'native' => 'à°¤à±†à°²à±�à°—à±�'),
		'kn'          => array('name' => 'Kannada',                'script' => 'Knda', 'dir' => 'ltr', 'native' => 'à²•à²¨à³�à²¨à²¡'),
		'ml'          => array('name' => 'Malayalam',              'script' => 'Mlym', 'dir' => 'ltr', 'native' => 'à´®à´²à´¯à´¾à´³à´‚'),
		'si'          => array('name' => 'Sinhala',                'script' => 'Sinh', 'dir' => 'ltr', 'native' => 'à·ƒà·’à¶‚à·„à¶½'),
		'th'          => array('name' => 'Thai',                   'script' => 'Thai', 'dir' => 'ltr', 'native' => 'à¹„à¸—à¸¢'),
		'lo'          => array('name' => 'Lao',                    'script' => 'Laoo', 'dir' => 'ltr', 'native' => 'àº¥àº²àº§'),
		'bo'          => array('name' => 'Tibetan',                'script' => 'Tibt', 'dir' => 'ltr', 'native' => 'à½”à½¼à½‘à¼‹à½¦à¾�à½‘à¼‹'),
		'dz'          => array('name' => 'Dzongkha',               'script' => 'Tibt', 'dir' => 'ltr', 'native' => 'à½¢à¾«à½¼à½„à¼‹à½�'),
		'my'          => array('name' => 'Burmese',                'script' => 'Mymr', 'dir' => 'ltr', 'native' => 'á€™á€¼á€”á€ºá€™á€¬á€˜á€¬á€žá€¬'),
		'ka'          => array('name' => 'Georgian',               'script' => 'Geor', 'dir' => 'ltr', 'native' => 'áƒ¥áƒ�áƒ áƒ—áƒ£áƒšáƒ˜'),
		'byn'         => array('name' => 'Blin',                   'script' => 'Ethi', 'dir' => 'ltr', 'native' => 'á‰¥áˆŠáŠ•'),
		'tig'         => array('name' => 'Tigre',                  'script' => 'Ethi', 'dir' => 'ltr', 'native' => 'á‰µáŒ�áˆ¨'),
		'ti'          => array('name' => 'Tigrinya',               'script' => 'Ethi', 'dir' => 'ltr', 'native' => 'á‰µáŒ�áˆ­áŠ›'),
		'am'          => array('name' => 'Amharic',                'script' => 'Ethi', 'dir' => 'ltr', 'native' => 'áŠ áˆ›áˆ­áŠ›'),
		'wal'         => array('name' => 'Wolaytta',               'script' => 'Ethi', 'dir' => 'ltr', 'native' => 'á‹ˆáˆ‹á‹­á‰³á‰±'),
		'chr'         => array('name' => 'Cherokee',               'script' => 'Cher', 'dir' => 'ltr', 'native' => 'á�£áŽ³áŽ©'),
		'iu'          => array('name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'dir' => 'ltr', 'native' => 'á�ƒá“„á’ƒá‘Žá‘�á‘¦'),
		'oj'          => array('name' => 'Ojibwa',                 'script' => 'Cans', 'dir' => 'ltr', 'native' => 'á�Šá“‚á”‘á“ˆá�¯á’§á�Žá“�'),
		'cr'          => array('name' => 'Cree',                   'script' => 'Cans', 'dir' => 'ltr', 'native' => 'á“€á�¦á�ƒá”­á��á��á�£'),
		'km'          => array('name' => 'Khmer',                  'script' => 'Khmr', 'dir' => 'ltr', 'native' => 'áž—áž¶ážŸáž¶áž�áŸ’áž˜áŸ‚ážš'),
		'mn-Mong'     => array('name' => 'Mongolian (Mongolian)',  'script' => 'Mong', 'dir' => 'rtl', 'native' => 'á ®á £á ¨á ­á ­á £á ¯ á ¬á ¡á ¯á ¡'),
		'shi-Tfng'    => array('name' => 'Tachelhit (Tifinagh)',   'script' => 'Tfng', 'dir' => 'rtl', 'native' => 'âµœâ´°âµŽâ´°âµ£âµ‰âµ–âµœ'),
		'tzm'         => array('name' => 'Central Atlas Tamazight (Tifinagh)','script' => 'Tfng', 'dir' => 'rtl', 'native' => 'âµœâ´°âµŽâ´°âµ£âµ‰âµ–âµœ'),
		'yue'         => array('name' => 'Yue',                    'script' => 'Hant', 'dir' => 'ltr', 'native' => 'å»£å·žè©±'),
		'ja'          => array('name' => 'Japanese',               'script' => 'Jpan', 'dir' => 'ltr', 'native' => 'æ—¥æœ¬èªž'),
		'zh'          => array('name' => 'Chinese (Simplified)',   'script' => 'Hans', 'dir' => 'ltr', 'native' => 'ç®€ä½“ä¸­æ–‡'),
		'zh-Hant'     => array('name' => 'Chinese (Traditional)',  'script' => 'Hant', 'dir' => 'ltr', 'native' => 'ç¹�é«”ä¸­æ–‡'),
		'ii'          => array('name' => 'Sichuan Yi',             'script' => 'Yiii', 'dir' => 'ltr', 'native' => 'ê†ˆêŒ ê‰™'),
		'vai'         => array('name' => 'Vai (Vai)',              'script' => 'Vaii', 'dir' => 'ltr', 'native' => 'ê•™ê”¤'),
		'jv-Java'     => array('name' => 'Javanese (Javanese)',    'script' => 'Java', 'dir' => 'ltr', 'native' => 'ê¦§ê¦±ê¦—ê¦®'),
		'ko'          => array('name' => 'Korean',                 'script' => 'Hang', 'dir' => 'ltr', 'native' => 'í•œêµ­ì–´')
    ];       
